version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions-maintenance:
        patterns:
          - "*"
    labels:
      - "enhancement"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-maintenance:
        patterns:
          - "*"
    labels:
      - "enhancement"
